spring:
  config:
    activate:
      on-profile: "qa"
  application:
    name: cards
  datasource:
    url: jdbc:h2:mem:cardsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

build:
  version: "4.0"

cards:
  message: "Cards Service - QA"
  contactDetails:
    name: "Riverbank"
    email: "riverbank@example.com"
  onCallSupport:
    - (123) 456-7890
    - (987) 654-3210