server:
    port: 8071

spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations:
#            - "classpath:/config"
#            - "file:///Users//Admin/configserver/src/main/resources/config"
        git:
          uri: https://github.com/ttgiang275/river-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "DS231DS45DS4354DS35DS34"